# This testcase is part of GDB, the GNU debugger.
#
# Copyright 2026 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test that the --enable-packet=AlwaysNonStop gdbserver command line option
# causes GDB to operate gdbserver with target-non-stop mode enabled.

load_lib gdbserver-support.exp

require allow_gdbserver_tests

standard_testfile server.c

if { [build_executable "failed to prepare" $testfile $srcfile] == -1 } {
    return
}
set target_binfile [gdb_remote_download target $binfile]

save_vars { ::GDBFLAGS } {
    if { ![is_remote host] && ![is_remote target] } {
	set ::GDBFLAGS "$::GDBFLAGS -ex \"set sysroot\""
    }
    clean_restart $::testfile
}
gdb_test "disconnect" ".*"

# Start gdbserver with --enable-packet=AlwaysNonStop
set res [gdbserver_start "--enable-packet=AlwaysNonStop" $::target_binfile]
set protocol [lindex $res 0]
set port [lindex $res 1]

set res [gdb_target_cmd $protocol $port]
if { ![gdb_assert {$res == 0} "connect"] } {
    return
}

# Check that target-non-stop is on
gdb_test "maint show target-non-stop" \
    "Whether the target is always in non-stop mode is auto \\(currently on\\)\\." \
    "verify target-non-stop is on"

# continue to end
gdb_continue_to_end
