# Copyright 2024-2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/> .

# Test "backtrace", "backtrace -n", "finish", "up" and "return" commands for
# functions with trampoline calls.

require allow_fortran_tests

if {![test_compiler_info {ifx-*} f90]} {
    untested "This test is only applicable for IFX, which emits the\
	trampoline DIE in Dwarf."
    return
}

standard_testfile ".f90"
load_lib fortran.exp

# Initialize the test by running the program to the innermost
# function name "second".

proc init_test {} {
    global binfile srcfile inner_loc

    clean_restart ${binfile}
    if {![fortran_runto_main]} {
	return
    }

    # Set breakpoint inside the innermost function 'second'.
    gdb_breakpoint "$srcfile:$inner_loc"
    gdb_continue_to_breakpoint "innermost-body" ".*$srcfile:$inner_loc.*"
}

set inner_loc [gdb_get_line_number "second-breakpt"]
set middle_loc [gdb_get_line_number "first-breakpt"]
set outer_loc [gdb_get_line_number "main-outer-loc"]
set fill "\[^\r\n\]*"

# Test both O0 and O2 to verify trampoline handling works correctly
# with and without optimization.
foreach_with_prefix opt_level {O0 O2} {
    if {[build_executable "failed to prepare" ${testfile}_${opt_level} ${srcfile} \
	[list debug f90 "optimize=-${opt_level}"]]} {
	continue
    }

    set binfile "${testfile}_${opt_level}"

    if {[string match -nocase "O2" $opt_level]} {
	# At O2, parameters may be optimized out
	set inner_desc  "second \\(.*\\) at ${fill}$srcfile:$inner_loc"
	set middle_desc "first \\(.*\\) at ${fill}$srcfile:$middle_loc"
    } else {
	set inner_desc  "second \\(x=20, y=9\\) at ${fill}$srcfile:$inner_loc"
	set middle_desc "first \\(num1=16, num2=3\\) at ${fill}$srcfile:$middle_loc"
    }
    set outer_desc  ".* at .*$srcfile:$outer_loc"

    with_test_prefix "backtrace" {
	init_test

	# Limit the backtrace to 3 frames and ensure both frames for first
	# and second function are shown only and trampoline frames are filtered.
	gdb_test "backtrace 3" [multi_line \
	    "#$decimal.* $inner_desc" \
	    "#$decimal.* $middle_desc" \
	    "#$decimal.* $outer_desc.*"]
	}

    with_test_prefix "backtrace outerframes" {
	init_test

	gdb_test "backtrace -3" [multi_line \
	    "#$decimal.* $middle_desc" \
	    "#$decimal.* $outer_desc.*"]
    }

    if {[string match -nocase "O2" $opt_level]} {
	continue
    }

    with_test_prefix "finish" {
	init_test

	gdb_test "finish" [multi_line \
	    "Run till exit from #0 $fill second \\(x=20, y=9\\) $fill" \
	    "${fill}first \\(num1=16, num2=3\\)${fill}" \
	    "${fill}(\r\nValue returned is $valnum_re = 180)"]
    }

    with_test_prefix "up" {
	init_test

	gdb_test "up" [multi_line \
	    "#$decimal.* $middle_desc" \
	    "${fill}first = second \\(num1 \\+ 4, num2 \\* 3\\).*${fill}"]
    }

with_test_prefix "return" {
    init_test

    gdb_test "return" \
	".*first = second \\(num1 \\+ 4, num2 \\* 3\\) \\! first-breakpt" \
	"" "Make second return now.*y or n. $" "y"
}
}
