# Copyright 2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test the variable lookup.

require allow_fortran_tests

standard_testfile .f90
load_lib fortran.exp

if {[prepare_for_testing "failed to prepare" $testfile \
	${srcfile} {debug f90}]} {
    return
}

if {![fortran_runto_main]} {
    return
}

set bp_loc [gdb_get_line_number "break-here"]
gdb_breakpoint "$srcfile:$bp_loc"
gdb_continue_to_breakpoint "stop-at-bp" ".*$srcfile:$bp_loc.*"

set integer4 [fortran_int4]
gdb_test "print array" "= \\(1, 1, 1, 1, 1\\)"
gdb_test "ptype array" "type = $integer4 \\(-2:2\\)"
