# Copyright 2024-2026 Free Software Foundation, Inc.
# Copyright (C) 2025-2026 Intel Corporation.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test shadow stack backtrace for signal handling on linux.

require allow_ssp_tests {istarget "*-*-linux*"}

standard_testfile amd64-shadow-stack-signal.c

save_vars { ::env(GLIBC_TUNABLES) } {

    append_environment GLIBC_TUNABLES "glibc.cpu.hwcaps" "SHSTK"

    if { [prepare_for_testing "failed to prepare" ${testfile} ${srcfile} \
	  {debug additional_flags="-fcf-protection=return"}] } {
	return
    }

    if { ![runto_main] } {
	return
    }

    gdb_breakpoint "handler"
    gdb_test "continue" \
	".*Program received signal SIGUSR1, User defined signal 1.*" \
	"continue until signal"
    gdb_continue_to_breakpoint "continue to breakpoint in handler"

    # Test shadow stack backtrace including <sigframe token>.
    gdb_test "bt -shadow" \
	[multi_line \
	    "#0\[ \t\]*$hex in \[^\r\n\]+" \
	    "#1\[ \t\]*<sigframe token>" \
	    "#2\[ \t\]*$hex in \[^\r\n\]+" \
	    ".*" ] \
	"test shadow stack backtrace for signal handling."
}
