# Copyright 2025 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Ensure that 'layout asm' displays proper assembly even if line
# table is missing.
# This test runs the example program compiled without adding debug
# info.  It breaks at 'fun' function and asks for 'layout asm'.
# Then checks if proper assembly shows instead of
# '[ No Assembly Available ]' message.

require allow_tui_tests

tuiterm_env

standard_testfile

# Compile sourcefile with 'nodebug' to disable any debug info.
if {[build_executable "failed to prepare ${srcfile}" \
    ${binfile} ${srcfile} {nodebug}]} {
    return -1
}

set tui_asm_window_width 90

Term::clean_restart 24 ${tui_asm_window_width} $testfile
if {![Term::prepare_for_tui]} {
    unsupported "TUI not supported"
    return
}

if {![runto "fun"]} {
  return
}

# This puts us into TUI mode, and should display the ASM window.
Term::command_no_prompt_prefix "layout asm"
Term::check_box_contents "check asm box contents" 0 0 ${tui_asm_window_width} 15 "<fun>"
