# Copyright 2026 Free Software Foundation, Inc.
# Copyright (C) 2026 Intel Corporation.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Tests GDB's support for SYCL when there are function calls inside
# the optimized kernel.

load_lib sycl.exp

standard_testfile .cpp

set sycl_device_list [init_sycl_devices_list]
if {[llength $sycl_device_list] == 0} {
    unsupported "target does not support SYCL"
    return 0
}

# Set the -O2 flag explicitly.
if {[build_executable "failed to compile $srcfile" \
    "${binfile}" $srcfile {sycl debug "optimize=-O2"}]} {
    return -1
}

# Return the current line number.
proc get_current_line {} {
    global decimal gdb_prompt
    gdb_test_multiple "info line" "get current line" {
	-re "Line ($decimal).*$gdb_prompt $" {
	    pass $gdb_test_name
	    return $expect_out(1,string)
	}
	-re "$gdb_prompt $" {
	    fail $gdb_test_name
	    return 0
	}
    }
}

proc test_call_stack {device} {
    global srcfile valnum_re inferior_exited_re gdb_prompt

    set fourth_loc [gdb_get_line_number "ordinary-fourth-loc"]
    set third_loc $srcfile:[gdb_get_line_number "ordinary-third-loc"]
    set second_loc $srcfile:[gdb_get_line_number "ordinary-second-loc"]
    set first_loc $srcfile:[gdb_get_line_number "ordinary-first-loc"]
    set outer_loc $srcfile:[gdb_get_line_number "ordinary-outer-loc"]
    set inlined_inner_loc $srcfile:[gdb_get_line_number "inlined-inner-loc"]
    set inlined_middle_loc $srcfile:[gdb_get_line_number "inlined-middle-loc"]
    set inlined_outer_loc $srcfile:[gdb_get_line_number "inlined-outer-loc"]

    set fill "\[^\r\n\]*"

    set opt_val "$::decimal\|\<optimized out\>"
    set fourth_desc \
	"fourth \\(x4=($opt_val), y4=($opt_val)\\) at ${fill}$srcfile:$fourth_loc"
    set third_desc \
	"third \\((x|y)3=($opt_val), (x|y)3=($opt_val)\\) at ${fill}$third_loc"
    set second_desc \
	"second \\((x|y)2=($opt_val), (x|y)2=($opt_val)\\) at ${fill}$second_loc"
    set first_desc \
	"first \\((x|y)1=($opt_val), (x|y)1=($opt_val)\\) at ${fill}$first_loc"
    set outer_desc "${fill}operator\\(\\)${fill} at ${fill}$outer_loc"
    set inlined_inner_desc \
	"inlined_second ${fill} at ${fill}$inlined_inner_loc"
    set inlined_middle_desc \
	"inlined_first ${fill} at ${fill}$inlined_middle_loc"
    set inlined_outer_desc \
	"${fill}operator\\(\\)${fill} at ${fill}$inlined_outer_loc"

    # Test breaking on function names inside the kernel.
    gdb_breakpoint "$srcfile:fourth"

    # Continue to breakpoint inside the kernel.
    gdb_continue_to_breakpoint "innermost-body" ".*fourth.*"

    if {[is_xe_hpg $device] || [is_xe_hpc $device]} {
	setup_kfail "JIRA GSD/12638" "*-*-*"
    }
    # Limit the backtrace to 5 frames because frame #5
    # and beyond are implementation-specific to the SYCL runtime.
    gdb_test "backtrace 5" [multi_line \
				"#0${fill} $fourth_desc" \
				"#1${fill} $third_desc" \
				"#2${fill} $second_desc" \
				"#3${fill} $first_desc" \
				"#4${fill} $outer_desc.*"] \
	"first backtrace"

    delete_breakpoints
    # Test inlined function calls.
    gdb_breakpoint $inlined_inner_loc

    if {[is_xe_hpg $device] || [is_xe_hpc $device]} {
	setup_kfail "JIRA GSD/12638" "*-*-*"
    }
    gdb_continue_to_breakpoint "inlined-body" ".*$inlined_inner_loc.*"

    if {[is_xe_hpg $device] || [is_xe_hpc $device]} {
	setup_kfail "JIRA GSD/12638" "*-*-*"
    }
    gdb_test "backtrace 3" [multi_line \
				"#0${fill} $inlined_inner_desc" \
				"#1${fill} $inlined_middle_desc" \
				"#2${fill} $inlined_outer_desc.*"] \
	"backtrace for inlined calls"

    delete_breakpoints
    # Now we will stop at the beginning of prologue of the fourth function
    # and instruction step through the function until it returns back
    # to the third.
    gdb_breakpoint "*fourth"

    if {[is_xe_hpg $device] || [is_xe_hpc $device]} {
	setup_kfail "JIRA GSD/12368" "*-*-*"
    }
    gdb_test "continue" "fourth.*$srcfile.*" "continue to fourth prologue"
    set i 0
    set current_line [get_current_line]
    set fourth_prologue_line $current_line

    # Update description to not include arguments.
    set third_desc "third ${fill} at ${fill}$third_loc"
    set second_desc "second ${fill} at ${fill}$second_loc"
    set first_desc "first ${fill} at ${fill}$first_loc"

    # Print the current instruction and framedesc for logging purposes.
    gdb_test "display/i \$pc"
    if {[is_xe_hpg $device]} {
	setup_kfail "JIRA GSD/12368" "*-*-*"
    }
    gdb_test "display/x \$framedesc"

    # Check the backtrace at each instruction until the return.  We do not
    # check the args here, as they might be invalid at prologue and epilogue.
    # Also check that there are no additional messages after
    # the backtrace except "(More stack frames follow...)".
    while {($current_line == $fourth_prologue_line
	    || $current_line == $fourth_loc)
	   && $i < 100} {
	with_test_prefix "iteration $i" {
	    if {[require_sycl_device "$device" "gpu" "Intel*"]} {
		set fourth_desc "fourth ${fill} at ${fill}$srcfile:$current_line"
		setup_kfail "JIRA GSD/12638" "*-*-*"
		gdb_test "backtrace 6" [multi_line \
					    "#0${fill} $fourth_desc" \
					    "#1${fill} $third_desc" \
					    "#2${fill} $second_desc" \
					    "#3${fill} $first_desc" \
					    "#4${fill} main${fill}operator${fill}lambda${fill} at .*" \
					    "#5${fill}(\r\n\\(More stack frames follow\\.\\.\\.\\))?"] \
		    "backtrace in fourth"
	    } else {
		# On CPU the backtrace in prologue might include additional RT specific frames.
		# Do not assume any frame numbers and do a deeper backtrace.
		# Do not expect the line number at fourth.
		# We expect to see our frames somewhere in the middle.
		set fourth_desc "fourth ${fill} at ${fill}$srcfile:$::decimal"
		gdb_test "backtrace 10" [multi_line \
					     "${fill} $fourth_desc" \
					     "${fill} $third_desc" \
					     "${fill} $second_desc" \
					     "${fill} $first_desc" \
					     "${fill} main${fill}operator${fill}lambda${fill} at .*"] \
		    "backtrace in fourth"
	    }
	    gdb_test "stepi"
	    incr i
	    set current_line [get_current_line]
	}
    }

    # Disable printing of PC and FRAMEDESC.
    gdb_test "undisplay 1-2"
}

foreach device $sycl_device_list {
    clean_restart "${binfile}"
    sycl_with_intelgt_lock $device {
	if {![sycl_start $device]} {
	    continue
	}
	test_call_stack "$device"
    }
}
