# Copyright (C) 2025 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Test the'-thread-filter' command for the intelgt target.

load_lib sycl.exp
load_lib mi-support.exp

standard_testfile "intelgt-info-threads.cpp"

set sycl_device_list [init_sycl_devices_list]
if {[llength $sycl_device_list] == 0} {
    unsupported "target does not support SYCL"
    return 0
}

if {[build_executable "failed to compile $srcfile" \
    "${binfile}" $srcfile {sycl debug}]} {
    return -1
}

set all_lanes "--all-lanes --s"
set selected_lanes "--selected-lanes --s"

proc test_thread_filter {device cmd num_filtered_threads} {
    set num_threads 0
    set command "-thread-filter $cmd"
    gdb_test_multiple " $command" "$device: $command" {
	-re "\\^done\\(,threads=\\\[\\)?" {
	    exp_continue
	}
	-re "state=\"stopped\"" {
	    incr num_threads
	    exp_continue
	}
	-re ".*$::mi_gdb_prompt" {
	    gdb_assert {$num_threads == $num_filtered_threads} \
		"$device: $command : $num_threads"
	}
    }
}

foreach device $sycl_device_list {
    sycl_with_intelgt_lock $device {
	if {![require_sycl_device "$device" "gpu" "Intel*"]} {
	    unsupported "test is aimed at Intel GPUs only"
	    continue
	}

	mi_clean_restart $binfile

	if {![mi_runto_main [sycl_get_device_args $device]]} {
	    continue
	}

	# Set breakpoint inside the kernel.
	set line [gdb_get_line_number "then-branch"]

	# Hit the kernel breakpoint.
	mi_continue_to_line $line \
	    "Continue to 'then-branch' and stop at breakpoint"

	set stopped_threads [mi_stopped_thread_ids $srcfile $line]
	set second_thread_id [lindex $stopped_threads 1]

	test_thread_filter device "$all_lanes \$_gthread == $second_thread_id" 1
	test_thread_filter device "$all_lanes dim0 == 22" 1
	test_thread_filter device "$selected_lanes dim0 == 22" 0
    }
}
