# Copyright 2025-2026 Free Software Foundation, Inc.
# Copyright (C) 2025-2026 Intel Corporation.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Test that IntelGT devices do not allow running function calls of different
# kernels.

load_lib sycl.exp

standard_testfile .cpp

set sycl_device_list [init_sycl_devices_list]
if {[llength $sycl_device_list] == 0} {
    unsupported "target does not support SYCL"
    return 0
}

if {[build_executable "failed to compile $srcfile" \
    "${binfile}" $srcfile {sycl debug}]} {
    return -1
}

foreach device $sycl_device_list {

    sycl_with_intelgt_lock $device {
	if {![require_sycl_device "$device" "gpu" "Intel*"]} {
	    unsupported "test is aimed at Intel GPUs only"
	    continue
	}

	clean_restart "${binfile}"

	if {![sycl_start $device]} {
	    continue
	}

	set kernel_1 [gdb_get_line_number "kernel-1-line"]
	set kernel_2 [gdb_get_line_number "kernel-2-line"]
	gdb_breakpoint $kernel_1 {temporary}
	gdb_breakpoint $kernel_2 {temporary}

	gdb_continue_to_breakpoint "hit bp in kernel 1" \
	    "$srcfile:$kernel_1.*"
	gdb_test "print add_one (1)" "= 2" \
	    "call kernel_1 function from kernel_1"
	gdb_test "print add (2, 3)" "= 5" \
	    "correct function lookup in kernel_1"

	gdb_continue_to_breakpoint "hit bp in kernel 2" \
	    "$srcfile:$kernel_2.*"
	gdb_test "print add_one (1)" "Cannot call a function from a different kernel\\." \
	    "call kernel_1 function from kernel_2"
	gdb_test "print add_two (1)" "= 3" \
	    "call kernel_2 function from kernel_2"
	gdb_test "print add (7, 8)" "= 15" \
	    "correct function lookup in kernel_2"
    }
}
