# Copyright 2019-2026 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Test stepping inside kernels.

load_lib sycl.exp

standard_testfile call-stack.cpp

set sycl_device_list [init_sycl_devices_list]
if {[llength $sycl_device_list] == 0} {
    unsupported "target does not support SYCL"
    return
}

if {[build_executable "failed to compile $srcfile" "$binfile" "$srcfile" \
	 {sycl debug}]} {
    return
}

foreach device $sycl_device_list {
    sycl_with_intelgt_lock $device {
	clean_restart $testfile

	if {![sycl_start $device]} {
	    continue
	}

	set outer_loc [gdb_get_line_number "ordinary-outer-loc"]
	gdb_breakpoint $outer_loc
	gdb_continue_to_breakpoint "inside" ".*$srcfile:$outer_loc.*"

	gdb_test "step" "first .* at .*" "step into function"
	gdb_test "next" "kernel-function-return.*"
    }
}
